[template.environment]
  NEXT_PUBLIC_SITE_NAME=""
  NEXT_PUBLIC_SITE_URL=""

  CL_CLIENT_ID=""
  CL_ENDPOINT=""

  NEXT_PUBLIC_SANITY_PROJECT_TITLE=""
  NEXT_PUBLIC_SANITY_PROJECT_ID=""
  NEXT_PUBLIC_SANITY_DATASET=""
  NEXT_PUBLIC_SANITY_API_VERSION=""
  NEXT_PUBLIC_SANITY_TOKEN=""
